USE CLASS101;

SELECT * FROM CATEGORY;
SELECT * FROM CLASS;
SELECT * FROM COMMENT;
SELECT * FROM CURRICULUM;
SELECT * FROM MEMBER;
SELECT * FROM REQUEST;
SELECT * FROM SUBCATEGORY;
SELECT * FROM SUBSCRIBE;
SELECT * FROM TEACHER;
SELECT * FROM THUMBNAIL;
SELECT * FROM VIDEO;
        
INSERT INTO MEMBER(ME_NAME, ME_ID, ME_PW, ME_NICK, ME_EMAIL, ME_NUMBER)
VALUES("정순형", "acejsh77", "1836", "TENET", "ace@kh.com", "010-2978-5497");

INSERT INTO REQUEST(RQ_ME_NUM, RQ_CONTENT)
VALUES(1, "강사 원츄");

INSERT INTO CLASS (CL_TITLE,CL_ITEM,CL_INTRO,CL_MONEY,CL_LEVEL,CL_TC_ME_NUM)
VALUES("ㅁㄴㅇ","ㅁㄴㅇ","ㅁㄴㅇ",1500,"상",3);