USE CLASS101;

SELECT * FROM CATEGORY;
SELECT * FROM CLASS;
SELECT * FROM COMMENT;
SELECT * FROM CURRICULUM;
SELECT * FROM MEMBER;
SELECT * FROM REQUEST;
SELECT * FROM SUBCATEGORY;
SELECT * FROM SUBSCRIBE;
SELECT * FROM TEACHER;
SELECT * FROM THUMBNAIL;
SELECT * FROM VIDEO;

SET GLOBAL event_scheduler = On; #이벤트 켜기

SHOW EVENTS; #이벤트 확인

# 이벤트 실행날짜 변경
ALTER EVENT delete_subscribe_event_5_2
ON SCHEDULE AT '2025-04-28 12:09:00';